INITIALIZE = b"\x1b\x40"

SET_JUSTIFICATION   = b"\x1B\x61"
JUSTIFY_LEFT        = SET_JUSTIFICATION + b"\x00"
JUSTIFY_CENTER      = SET_JUSTIFICATION + b"\x01"
JUSTIFY_RIGHT       = SET_JUSTIFICATION + b"\x02"

RESET_PRINT_MODE    = b"\x1b\x21\x00"
BOLD_OFF            = b"\x1b\x45\x00"
BOLD_ON             = b"\x1b\x45\x01"
UNDERLINE_OFF       = b"\x1b\x2d\x00"
UNDERLINE_ONE       = b"\x1b\x2d\x01"
UNDERLINE_TWO       = b"\x1b\x2d\x02"
FONT_A              = b"\x1B\x4d\x00"
FONT_B              = b"\x1B\x4d\x01"
SELECT_PRINT_MODE   = b"\x1b\x21"

START_PAGE_MODE     = b"\x1b\x4c"
PAGE_UPSIDEDOWN     = b"\x1b\x54\x02"
PAGE_AREA_SETUP     = b"\x1b\x57"
PAGE_PRINT_RETURN   = b"\x0c"

RESET_LINE_SPACING  = b"\x1b\x32"
EDIT_LINE_SPACING   = b"\x1b\x33"
SET_IMAGE_SPACING   = EDIT_LINE_SPACING + b"\x18"
START_BIT_IMAGE     = b"\x1b\x2a\x21"
START_BUFFERED_IMAGE= b"\x1d\x28\x4c"
PRINT_BUFFERED_IMAGE= START_BUFFERED_IMAGE + b"\x02\x00\x30\x32"

CUT_FULL            = b"\x1D\x56\x00"
CUT_PARTIAL         = b"\x1D\x56\x01"
FEED_AND_CUT_FULL   = b"\x1D\x56\x41\x10"
FEED_AND_CUT_PARTIAL= b"\x1D\x56\x42\x10"